[versions]
javalin = "6.7.0"
hikaricp = "5.1.0"
slf4j = "2.0.13"
log4j = "2.23.1"
javaJwt = "4.4.0"
jbcrypt = "0.4"
mysqlConnector = "9.0.0"
jackson = "2.17.2"
junit = "5.10.3"
assertj = "3.26.3"
mockito = "5.14.2"
lombok = "1.18.32"
jakartaValidation = "3.0.2"
jakartaPersistence = "3.1.0"
guice = "7.0.0"

[libraries]
javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
javalinTesttools = { module = "io.javalin:javalin-testtools", version.ref = "javalin" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
log4jCore = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4jApi = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4jSlf4j = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
javaJwt = { module = "com.auth0:java-jwt", version.ref = "javaJwt" }
jbcrypt = { module = "org.mindrot:jbcrypt", version.ref = "jbcrypt" }
mysqlConnector = { module = "com.mysql:mysql-connector-j", version.ref = "mysqlConnector" }
jacksonJsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
jakartaValidation = { module = "jakarta.validation:jakarta.validation-api", version.ref = "jakartaValidation" }
jakartaPersistence = { module = "jakarta.persistence:jakarta.persistence-api", version.ref = "jakartaPersistence" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
